### ISSUE TITLE
Incompatibility with MonadRandom-0.5

### ISSUE THREAD

**Issue by jvilar** [mstksg/auto#18]
I am trying to install auto-0.4.3.0 in a system with the 0.5 version of MonadRandom and it fails with errors when compiling Random.hs. It looks like those errors are related to the new version of MonadRandom. This is the [log file](https://github.com/mstksg/auto/files/702157/auto-0.4.3.0.log.txt).

**Comment by mstksg** [comment]
Thanks for bringing this to my attention.  Should be fixed with v0.4.3.1 :) https://github.com/mstksg/auto/releases/tag/v0.4.3.1
