### ISSUE TITLE
Problem with tutorial or me?

### ISSUE THREAD

**Issue by psycotica0** [mstksg/auto#9]
In the tutorial, just above the section on proc notation, you've got the auto `foo`.

The tutorial says the first output is `(4, Just 4)`, but wouldn't it be `(8, Just 4)`?

First `x` goes in to `sumX` which returns `4`, but then we add `x + sumX`, which is `4 + 4`, right?
That goes into `prodX`, which just returns `8`.

`lastEven` appears to just pull from `x`, so it'd just be `Just 4`.

I can't actually install or run `auto` on my computer to check, but I wanted to check just in case my understanding is wrong.

**Comment by mstksg** [comment]
Thanks :)  You're right, the tutorial is wrong on that line.  The rest of the output is correct, it's just that `4`.  I've uploaded a corrected version :)
